export const mySkills = [
  { title: "HTML", icon: "html" },
  { title: "CSS", icon: "css" },
  { title: "JavaScript", icon: "javascript" },
  { title: "ReactJS", icon: "react" },
  { title: "NextJS", icon: "nextjs" },
  { title: "Tailwind CSS", icon: "tailwind" },
  { title: "NodeJS", icon: "nodejs" },
  { title: "ExpressJS", icon: "express" },
  { title: "MongoDB", icon: "mongodb" },
  { title: "Git", icon: "git" },
  { title: "GitHub", icon: "gitHub" },
  { title: "Postman", icon: "postman" },
  { title: "Linux", icon: "linux" },
  { title: "macOS", icon: "macos" },
  { title: "Windows", icon: "windows" },
  { title: "npm", icon: "npm" },
  { title: "Docker", icon: "docker" },
];
